<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> :: About :: Mini Framework PHP </title>
    <link rel="stylesheet" href="<?= $this->view->css ?>">
</head>
<body>

    <h1> About </h1>

    <div>
        Esta página utiliza uma folha de estilos personalizada, disponível no folder "css" do diretório public. 
        <p> 
            Uma folha de estilos pode ser facilmente referenciada ao renderizar uma view, <br>
            passando o nome da folha de estilos como parâmetro e recuperando-o na view através do atributo css do objeto view. <br><br>
            
            <small> Aplicável também a arquivos JavaScript. </small>
        </p>
    </div>
    
</body>
</html>