<?php $layout = 'default'; ?>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> :: Mini Framework PHP :: </title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>

    <nav class="navbar-main">
        <ul>
            <li class="item-menu"> <a href="/home"> Home </a> </li>
            <li class="item-menu"> <a href="/about"> Sobre </a> </li>
            <li class="item-menu"> <a href="#"> Começando </a> </li>
        </ul>
    </nav>

    <?= $this->content() ?>

    <footer>
        <p> Desenvolvido por <a href="https://github.com/felipewesley" class="link-author" title="Perfil de Felipe Wesley" target="_blank"> Felipe Wesley </a> </p>
        <button class="btn btn-dark" onclick="openProject();" id="gotoproject" title="Mini Framework PHP no GitHub"> Ver projeto no GitHub </button>
    </footer>

</body>
</html>
